const ingredients = [
  {
    name: "Pineapple",
    price: 199,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Olives",
    price: 99,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Green Peppers",
    price: 149,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Onions",
    price: 99,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Mushrooms",
    price: 149,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Green Olives",
    price: 149,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Black Olives",
    price: 149,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Sausage",
    price: 249,
    category: "Toppings",
    veggie: false,
  },
  {
    name: "Pepperoni",
    price: 199,
    category: "Toppings",
    veggie: false,
  },
  {
    name: "Blue Cheese",
    price: 299,
    category: "Cheese",
    veggie: false,
  },
  {
    name: "Goat Cheese",
    price: 349,
    category: "Cheese",
    veggie: true,
  },
  {
    name: "Cheddar Cheese",
    price: 299,
    category: "Cheese",
    veggie: true,
  },
  {
    name: "Mozzarella Cheese",
    price: 299,
    category: "Cheese",
    veggie: true,
  },
  {
    name: "Parmesan Cheese",
    price: 349,
    category: "Cheese",
    veggie: true,
  },
  {
    name: "Bacon",
    price: 249,
    category: "Toppings",
    veggie: false,
  },
  {
    name: "Ham",
    price: 249,
    category: "Toppings",
    veggie: false,
  },
  {
    name: "Anchovies",
    price: 349,
    category: "Toppings",
    veggie: false,
  },
  {
    name: "Artichokes",
    price: 249,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Prosciutto",
    price: 349,
    category: "Toppings",
    veggie: false,
  },
  {
    name: "Salami",
    price: 249,
    category: "Toppings",
    veggie: false,
  },
  {
    name: "Canadian Bacon",
    price: 249,
    category: "Toppings",
    veggie: false,
  },
  {
    name: "Chicken",
    price: 199,
    category: "Toppings",
    veggie: false,
  },
  {
    name: "Shrimp",
    price: 299,
    category: "Toppings",
    veggie: false,
  },
  {
    name: "Tuna",
    price: 249,
    category: "Toppings",
    veggie: false,
  },
  {
    name: "Feta Cheese",
    price: 249,
    category: "Cheese",
    veggie: true,
  },
  {
    name: "Gouda Cheese",
    price: 299,
    category: "Cheese",
    veggie: true,
  },
  {
    name: "Ricotta Cheese",
    price: 199,
    category: "Cheese",
    veggie: true,
  },
  {
    name: "Smoked Mozzarella Cheese",
    price: 299,
    category: "Cheese",
    veggie: true,
  },
  {
    name: "Asiago Cheese",
    price: 299,
    category: "Cheese",
    veggie: true,
  },
  {
    name: "Fontina Cheese",
    price: 299,
    category: "Cheese",
    veggie: true,
  },
  {
    name: "Brie Cheese",
    price: 399,
    category: "Cheese",
    veggie: true,
  },
  {
    name: "Pepper Jack Cheese",
    price: 249,
    category: "Cheese",
    veggie: true,
  },
  {
    name: "Jalapenos",
    price: 99,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Banana Peppers",
    price: 99,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Basil",
    price: 89,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Bell peppers",
    price: 79,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Broccoli",
    price: 99,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Capers",
    price: 89,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Chorizo",
    price: 119,
    category: "Toppings",
    veggie: false,
  },
  {
    name: "Gorgonzola cheese",
    price: 99,
    category: "Cheese",
    veggie: false,
  },
  {
    name: "Kimchi",
    price: 109,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Mixed greens",
    price: 79,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Mustard greens",
    price: 89,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Nutritional yeast",
    price: 99,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Poblano peppers",
    price: 89,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Roasted red peppers",
    price: 89,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Scallions",
    price: 69,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Sweet corn",
    price: 79,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Thyme",
    price: 79,
    category: "Toppings",
    veggie: true,
  },
  {
    name: "Avocado",
    price: 129,
    category: "Toppings",
    veggie: true,
  },
];

module.exports = ingredients;
