const ingredients = [
  { name: "Albahaca", category: "Toppings", veggie: true, extra: true, price: 100 },
  { name: "Garlic", category: "Toppings", veggie: true, extra: true, price: 50 },
  { name: "Spinach", category: "Toppings", veggie: true, extra: false, price: 200 }, 
  { name: "Cucumber", category: "Toppings", veggie: true, extra: false, price: 200 }, 
  { name: "Lettuce", category: "Toppings", veggie: true, extra: false, price: 100 }, 
  { name: "Arugula", category: "Toppings", veggie: true, extra: false, price: 300 }, 
  { name: "Mortadella", category: "Proteins", veggie: false, extra: true, price: 350 },
  { name: "Oregano", category: "Toppings", veggie: true, extra: false, price: 50 },
  { name: "Caesar sauce", category: "Toppings", veggie: true, extra: false, price: 300 },
  { name: "Parsley", category: "Toppings", veggie: true, extra: false, price: 150 },
  { name: "Pesto", category: "Toppings", veggie: true, extra: false, price: 100 },
  { name: "Provolone", category: "Cheese", veggie: true, extra: true, price: 200 },
  { name: "Beef", category: "Meat", veggie: false, extra: false, price: 500 },
  { name: "Steak", category: "Meat", veggie: false, extra: false, price: 400 },
  { name: "Meatballs", category: "Meat", veggie: false, extra: true, price: 400 },
  { name: "Mozzarella", category: "Cheese base", veggie: true, extra: true, price: 400 },
  {name: "Lactose-Free Mozzarella",category: "Cheese base",veggie: true,price: 460},
  {name: "Vegan Mozzarella", category: "Cheese base",veggie: true,price: 500},
  { name: "No Mozzarella", category: "Cheese base", veggie: true, price: 0 },
  { name: "Tomato sauce", category: "Sauce base", veggie: true, extra: true, price: 300 },
  { name: "Milk cream", category: "Sauce base", veggie: false, extra: true, price: 400 },
  { name: "White sauce", category: "Sauce base", veggie: false, extra: true, price: 400 },
  { name: "No sauce", category: "Sauce base", veggie: true, extra:false, price: 0 },
  { name: "Gluten-Free", category: "Dough", veggie: true, extra:false, price: 250 },
  { name: "Wholemeal flour", category: "Dough", veggie: true, extra:false,price: 210 },
  { name: "Wheat flour", category: "Dough", veggie: true, extra:false, price: 100 },
  { name: "Thin", category: "Type", veggie: null,  extra:false, price: 200 },
  { name: "Gross", category: "Type", veggie: null,  extra:false, price: 250 },
  {name: "Tomatoes",category: "Toppings",veggie: true, extra: false, price: 150},
  {name: "Lomo", category: "Proteins", veggie: false, extra:false, price: 300},
  {name: "Fried Egg", category: "Toppings", veggie: true, extra:true, price: 200},
  { name: "Pineapple",category: "Toppings",veggie: true, extra:true, price: 300},
  {
    name: "Green Peppers",
    category: "Toppings",
    extra:true, 
    veggie: true,
    price: 250,
  },
  {
    name: "Onions",
    price: 200,
    category: "Toppings",
    extra:true, 
    veggie: true,
  },
  {
    name: "Red Onions",
    price: 200,
    category: "Toppings",
    extra:true, 
    veggie: true,
  },
  {
    name: "Mushrooms",
    price: 200,
    category: "Toppings",
    extra:true, 
    veggie: true,
  },
  {
    name: "Green Olives",
    price: 150,
    category: "Toppings",
    extra:true, 
    veggie: true,
  },
  {
    name: "Black Olives",
    price: 150,
    category: "Toppings",
    extra:true, 
    veggie: true,
  },
  {
    name: "Sausage",
    price: 300,
    category: "Meat",
    extra:true, 
    veggie: false,
  },
  {
    name: "Pepperoni",
    price: 400,
    category: "Meat",
    extra:true, 
    veggie: false,
  },
  {
    name: "Blue Cheese",
    price: 250,
    category: "Cheese",
    extra:true, 
    veggie: false,
  },
  {
    name: "Goat Cheese",
    price: 300,
    category: "Cheese",
    extra:true, 
    veggie: true,
  },
  {
    name: "Cheddar Cheese",
    price: 250,
    category: "Cheese",
    extra:true, 
    veggie: true,
  },
  {
    name: "Parmesan Cheese",
    price: 250,
    category: "Cheese",
    extra:true, 
    veggie: true,
  },
  {
    name: "Bacon",
    price: 400,
    category: "Meat",
    extra:true, 
    veggie: false,
  },
  {
    name: "Ham",
    price: 350,
    category: "Meat",
    extra:true, 
    veggie: false,
  },
  {
    name: "Anchovies",
    price: 400,
    category: "Meat",
    extra:true, 
    veggie: false,
  },
  {
    name: "Artichokes",
    price: 150,
    category: "Toppings",
    extra:false, 
    veggie: true,
  },
  {
    name: "Prosciutto",
    price: 250,
    category: "Toppings",
    extra:true, 
    veggie: false,
  },
  {
    name: "Salami",
    price: 250,
    category: "Toppings",
    extra:true, 
    veggie: false,
  },
  {
    name: "Canadian Bacon",
    price: 300,
    category: "Toppings",
    extra:false, 
    veggie: false,
  },
  {
    name: "Chicken",
    price: 400,
    category: "Meat",
    extra:true, 
    veggie: false,
  },
  {
    name: "Shrimp",
    price: 600,
    category: "Toppings",
    extra:true, 
    veggie: false,
  },
  {
    name: "Tuna",
    price: 400,
    category: "Toppings",
    extra:true, 
    veggie: false,
  },
  {
    name: "Feta Cheese",
    price: 250,
    category: "Cheese",
    extra:true, 
    veggie: true,
  },
  {
    name: "Gouda Cheese",
    price: 300,
    category: "Cheese",
    extra:true, 
    veggie: true,
  },
  {
    name: "Ricotta Cheese",
    price: 250,
    category: "Cheese",
    extra:true, 
    veggie: true,
  },
  {
    name: "Smoked Mozzarella Cheese",
    price: 250,
    category: "Cheese",
    extra:true, 
    veggie: true,
  },
  {
    name: "Asiago Cheese",
    price: 250,
    category: "Cheese",
    extra:true, 
    veggie: true,
  },
  {
    name: "Fontina Cheese",
    price: 250,
    category: "Cheese",
    extra:true, 
    veggie: true,
  },
  {
    name: "Brie Cheese",
    price: 300,
    category: "Cheese",
    extra:true, 
    veggie: true,
  },
  {
    name: "Pepper Jack Cheese",
    price: 300,
    category: "Cheese",
    extra:true, 
    veggie: true,
  },
  {
    name: "Jalapenos",
    price: 270,
    category: "Toppings",
    extra:true, 
    veggie: true,
  },
  {
    name: "Banana Peppers",
    price: 260,
    category: "Toppings",
    extra:true, 
    veggie: true,
  },
  {
    name: "Basil",
    price: 100,
    category: "Toppings",
    extra:true, 
    veggie: true,
  },
  {
    name: "Bell peppers",
    price: 200,
    category: "Toppings",
    extra:false, 
    veggie: true,
  },
  {
    name: "Eggplant",
    price: 200,
    category: "Toppings",
    extra:true, 
    veggie: true,
  },
  {
    name: "Broccoli",
    price: 300,
    category: "Toppings",
    extra:false, 
    veggie: true,
  },
  {
    name: "Capers",
    price: 200,
    category: "Toppings",
    extra:false, 
    veggie: true,
  },
  {
    name: "Chorizo",
    price: 300,
    category: "Toppings",
    extra:true, 
    veggie: false,
  },
  {
    name: "Gorgonzola cheese",
    price: 250,
    category: "Cheese",
    extra:true, 
    veggie: false,
  },
  {
    name: "Mixed greens",
    price: 150,
    category: "Toppings",
    extra:false, 
    veggie: true,
  },
  {
    name: "Mustard greens",
    price: 150,
    category: "Toppings",
    extra:false, 
    veggie: true,
  },
  {
    name: "Nutritional yeast",
    price: 160,
    category: "Toppings",
    extra:false, 
    veggie: true,
  },
  {
    name: "Poblano peppers",
    price: 280,
    category: "Toppings",
    extra:true, 
    veggie: true,
  },
  {
    name: "Roasted red peppers",
    price: 280,
    category: "Toppings",
    extra:true, 
    veggie: true,
  },
  {
    name: "Scallions",
    price: 200,
    category: "Toppings",
    extra:true, 
    veggie: true,
  },
  {
    name: "Sweet corn",
    price: 150,
    category: "Toppings",
    extra:false, 
    veggie: true,
  },
  {
    name: "Thyme",
    price: 180,
    category: "Toppings",
    extra:false, 
    veggie: true,
  },
  {
    name: "Avocado",
    price: 400,
    category: "Toppings",
    extra:true,
    veggie: true,
  },
];
module.exports = ingredients;
