const itemList = [
  {
    name: "Margherita",
    price: 10.99,
    image: "https://i.postimg.cc/J4qsjrzR/margherita.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Pepperoni",
    price: 12.99,
    image: "https://i.postimg.cc/cLLrmpvw/pepperoni.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Meat lovers",
    price: 14.99,
    image: "https://i.postimg.cc/0yXrHVS3/meat-lovers.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Hawaiian",
    price: 12.99,
    image: "https://i.postimg.cc/h4VzPbFz/Hawaiian.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "BBQ chicken",
    price: 13.99,
    image: "https://i.postimg.cc/WbjDDFj9/BBQ-chicken.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Veggie",
    price: 12.99,
    image: "https://i.postimg.cc/fy7J2Z7j/veggie.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Four-cheese",
    price: 11.99,
    image: "https://i.postimg.cc/TPHmgRQK/four-cheese.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Greek",
    price: 12.99,
    image: "https://i.postimg.cc/Mpqy83vp/greek.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Buffalo chicken",
    price: 13.99,
    image: "https://i.postimg.cc/PfDZvnDq/buffalo-chicken.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Mushroom",
    price: 12.99,
    image: "https://i.postimg.cc/ZRGdsVGZ/mushroom.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Spinach and feta",
    price: 12.99,
    image: "https://i.postimg.cc/hjzm0H3p/Spinach-and-feta.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Pesto",
    price: 12.99,
    image: "https://i.postimg.cc/qM88SHBF/Pesto.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Sausage and mushroom",
    price: 13.99,
    image: "https://i.postimg.cc/Gh0FXmRY/Sausage-and-mushroom.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Philly cheesesteak",
    price: 14.99,
    image: "https://i.postimg.cc/rppxDdG6/Philly-cheesesteak.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Seafood",
    price: 15.99,
    image: "https://i.postimg.cc/PJQBVFC8/Seafood.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Roasted garlic and tomato pizza",
    price: 10.99,
    image: "https://i.postimg.cc/pdgbmjNy/Roasted-garlic-and-tomato-pizza.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Bacon and egg pizza",
    price: 12.99,
    image: "https://i.postimg.cc/ZRpkpqZH/Bacon-and-egg-pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Prosciutto and arugula pizza",
    price: 11.99,
    image: "https://i.postimg.cc/x11ShYyj/Prosciutto-and-arugula-pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Artichoke and goat cheese pizza",
    price: 13.99,
    image: "https://i.postimg.cc/sDyzP5Mh/Artichoke-and-goat-cheese-pizza.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Caramelized onion and bacon pizza",
    price: 10.99,
    image:
      "https://i.postimg.cc/C5CgTxQ5/Caramelized-onion-and-bacon-pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Roasted Vegetable Pizza",
    price: 12.99,
    image: "https://i.postimg.cc/3wyQrBcP/Roasted-Vegetable-Pizza.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Chicken and Broccoli Alfredo Pizza",
    price: 14.99,
    image:
      "https://i.postimg.cc/wxDHsw-jz/Chicken-and-Broccoli-Alfredo-Pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Mac and Cheese Pizza",
    price: 11.99,
    image: "https://i.postimg.cc/DyqZn2Xq/Mac-and-Cheese-Pizza.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Steak and Blue Cheese Pizza",
    price: 16.99,
    image: "https://i.postimg.cc/y8sNNwm2/Steak-and-Blue-Cheese-Pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Shrimp Scampi Pizza",
    price: 15.99,
    image: "https://i.postimg.cc/WzZ4DVfc/Shrimp-Scampi-Pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Chicken Caesar Salad Pizza",
    price: 13.99,
    image: "https://i.postimg.cc/L4g5Qk4Q/Chicken-Caesar-Salad-Pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Green Olive and Sausage Pizza",
    price: 14.99,
    image: "https://i.postimg.cc/DZJvDFh4/Green-Olive-and-Sausage-Pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Ricotta and Basil Pizza",
    price: 12.99,
    image: "https://i.postimg.cc/g00kV8BD/Ricotta-and-basil.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Barbecue Bacon Cheeseburger Pizza",
    price: 16.99,
    image:
      "https://i.postimg.cc/y8j83vnx/Barbecue-Bacon-Cheeseburger-Pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Tuna and Red Onion Pizza",
    price: 15.99,
    image: "https://i.postimg.cc/MKkTCcv6/Tuna-and-red-onion.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "Supreme",
    price: 14.99,
    image:
      "https://napolipizzalv.com/wp-content/uploads/2019/10/DSC_0905-min.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
    category: "pizza",
  },
  {
    name: "CocaCola 0.6 Liters",
    image: "https://i.postimg.cc/Z5y4bZQh/cocacola.png",
    price: 1.22,
    detail: { onSugar: "sugar", volumen: "600" },
    category: "drinks",
    rating: 5,
    stock: 0,
  },
  {
    name: "CocaCola 1 Liter",
    image: "https://i.postimg.cc/Z5y4bZQh/cocacola.png",
    price: 1.92,
    detail: { onSugar: "sugar", volumen: "1000",  },
    category: "drinks",
    rating: 4,
    stock: 0,
  },
  {
    name: "CocaCola 2 Liters",
    image: "https://i.postimg.cc/Z5y4bZQh/cocacola.png",
    price: 2.42,
    detail: { onSugar: "sugar", volumen: "2000" },
    category: "drinks",
    rating: 4,
    stock: 9,
  },
  {
    name: "Diet Coke 0.6 Liters",
    image: "https://i.postimg.cc/V6z8WtkY/dietcoke.png",
    price: 1.22,
    detail: { onSugar: "nosugar", volumen: "600" },
    category: "drinks",
    rating: 2,
    stock: 5,
  },
  {
    name: "Diet Coke 1 Liter",
    image: "https://i.postimg.cc/V6z8WtkY/dietcoke.png",
    price: 1.92,
    detail: { onSugar: "nosugar", volumen: "1000" },
    category: "drinks",
    rating: 2,
    stock: 5,
  },
  {
    name: "Diet Coke 2 Liters",
    image: "https://i.postimg.cc/V6z8WtkY/dietcoke.png",
    price: 2.42,
    detail: { onSugar: "nosugar", volumen: "2000" },
    category: "drinks",
    rating: 2,
    stock: 5,
  },
  {
    name: "Fanta",
    image: "https://i.postimg.cc/CKTYdXyn/fanta.png",
    price: 1.22,
    detail: { onSugar: "sugar" },
    category: "drinks",
    rating: 3,
    stock: 5,
  },
  {
    name: "Sprite",
    image: "https://i.postimg.cc/cHTN9Jvf/sprite.png",
    price: 1.22,
    detail: { onSugar: "sugar" },
    category: "drinks",
    rating: 3,
    stock: 0,
  },
  {
    name: "Water",
    image: "https://i.postimg.cc/rFHq2zQJ/agua.png",
    price: 1.15,
    detail: { onSugar: "nosugar" },
    category: "drinks",
    rating: 3,
    stock: 0,
  },
  {
    name: "Strawberry Fanta",
    image: "https://i.postimg.cc/yxdCwzRt/redfanta.png",
    price: 1.22,
    detail: { onSugar: "sugar" },
    category: "drinks",
    rating: 1,
    stock: 15,
  },
  {
    name: "RockStar Orange",
    image: "https://i.postimg.cc/436GcPZL/rockstarorange.png",
    price: 1.5,
    detail: { onSugar: "sugar" },
    category: "drinks",
    rating: 2,
    stock: 12,
  },
  {
    name: "Vitamin Water",
    image: "https://i.postimg.cc/FzPXmbJT/gatorade.png",
    price: 2.5,
    detail: { onSugar: "nosugar" },
    category: "drinks",
    rating: 1,
    stock: 12,
  },
];

module.exports = itemList;
