const pizzaList = [
  {
    name: "Margherita",
    price: 10.99,
    image: "https://i.postimg.cc/J4qsjrzR/margherita.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Pepperoni",
    price: 12.99,
    image: "https://i.postimg.cc/cLLrmpvw/pepperoni.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Meat lovers",
    price: 14.99,
    image: "https://i.postimg.cc/0yXrHVS3/meat-lovers.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Hawaiian",
    price: 12.99,
    image: "https://i.postimg.cc/h4VzPbFz/Hawaiian.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "BBQ chicken",
    price: 13.99,
    image: "https://i.postimg.cc/WbjDDFj9/BBQ-chicken.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Veggie",
    price: 12.99,
    image: "https://i.postimg.cc/fy7J2Z7j/veggie.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Four-cheese",
    price: 11.99,
    image: "https://i.postimg.cc/TPHmgRQK/four-cheese.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Greek",
    price: 12.99,
    image: "https://i.postimg.cc/Mpqy83vp/greek.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Buffalo chicken",
    price: 13.99,
    image: "https://i.postimg.cc/PfDZvnDq/buffalo-chicken.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Mushroom",
    price: 12.99,
    image: "https://i.postimg.cc/ZRGdsVGZ/mushroom.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Spinach and feta",
    price: 12.99,
    image: "https://i.postimg.cc/hjzm0H3p/Spinach-and-feta.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Pesto",
    price: 12.99,
    image: "https://i.postimg.cc/qM88SHBF/Pesto.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Sausage and mushroom",
    price: 13.99,
    image: "https://i.postimg.cc/Gh0FXmRY/Sausage-and-mushroom.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Philly cheesesteak",
    price: 14.99,
    image: "https://i.postimg.cc/rppxDdG6/Philly-cheesesteak.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Seafood",
    price: 15.99,
    image: "https://i.postimg.cc/PJQBVFC8/Seafood.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Roasted garlic and tomato pizza",
    price: 10.99,
    image: "https://i.postimg.cc/pdgbmjNy/Roasted-garlic-and-tomato-pizza.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Bacon and egg pizza",
    price: 12.99,
    image: "https://i.postimg.cc/ZRpkpqZH/Bacon-and-egg-pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Prosciutto and arugula pizza",
    price: 11.99,
    image: "https://i.postimg.cc/x11ShYyj/Prosciutto-and-arugula-pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Artichoke and goat cheese pizza",
    price: 13.99,
    image: "https://i.postimg.cc/sDyzP5Mh/Artichoke-and-goat-cheese-pizza.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Caramelized onion and bacon pizza",
    price: 10.99,
    image:
      "https://i.postimg.cc/C5CgTxQ5/Caramelized-onion-and-bacon-pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Roasted Vegetable Pizza",
    price: 12.99,
    image: "https://i.postimg.cc/3wyQrBcP/Roasted-Vegetable-Pizza.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Chicken and Broccoli Alfredo Pizza",
    price: 14.99,
    image:
      "https://i.postimg.cc/wxDHsw-jz/Chicken-and-Broccoli-Alfredo-Pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Mac and Cheese Pizza",
    price: 11.99,
    image: "https://i.postimg.cc/DyqZn2Xq/Mac-and-Cheese-Pizza.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Steak and Blue Cheese Pizza",
    price: 16.99,
    image: "https://i.postimg.cc/y8sNNwm2/Steak-and-Blue-Cheese-Pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Shrimp Scampi Pizza",
    price: 15.99,
    image: "https://i.postimg.cc/WzZ4DVfc/Shrimp-Scampi-Pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Chicken Caesar Salad Pizza",
    price: 13.99,
    image: "https://i.postimg.cc/L4g5Qk4Q/Chicken-Caesar-Salad-Pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Green Olive and Sausage Pizza",
    price: 14.99,
    image: "https://i.postimg.cc/DZJvDFh4/Green-Olive-and-Sausage-Pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Ricotta and Basil Pizza",
    price: 12.99,
    image: "https://i.postimg.cc/g00kV8BD/Ricotta-and-basil.png",
    vegetarian: true,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Barbecue Bacon Cheeseburger Pizza",
    price: 16.99,
    image:
      "https://i.postimg.cc/y8j83vnx/Barbecue-Bacon-Cheeseburger-Pizza.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Tuna and Red Onion Pizza",
    price: 15.99,
    image: "https://i.postimg.cc/MKkTCcv6/Tuna-and-red-onion.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
  {
    name: "Supreme",
    price: 14.99,
    image: "https://napolipizzalv.com/wp-content/uploads/2019/10/DSC_0905-min.png",
    vegetarian: false,
    // userId: null,
    detail: {
      dough: "wholemeal flour",
      type: "gross",
      base: "milk cream",
      mozzarella: "vegan mozarella",
      toppingIngredients: ["Pineapple", "Mushrooms"],
      cheeseIngredients: [
        "Fontina Cheese",
        "Asiago Cheese",
        "Smoked Mozzarella Cheese",
      ],
      meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
    },
  },
];

module.exports = pizzaList;
